-- 1. Create Buckets
INSERT INTO storage.buckets (id, name, public) 
VALUES ('employee-photos', 'employee-photos', false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public) 
VALUES ('attendance-photos', 'attendance-photos', false)
ON CONFLICT (id) DO NOTHING;

-- 2. Add new columns to existing tables
ALTER TABLE public.funcionarios ADD COLUMN IF NOT EXISTS photo_path text;

ALTER TABLE public.presencas ADD COLUMN IF NOT EXISTS photo_path text;
ALTER TABLE public.presencas ADD COLUMN IF NOT EXISTS photo_taken_at timestamptz;
ALTER TABLE public.presencas ADD COLUMN IF NOT EXISTS photo_taken_by uuid REFERENCES public.usuarios(id);

-- 3. Storage Policies
-- Note: Since the application uses a custom authentication system querying public.usuarios 
-- instead of Supabase GoTrue Auth, auth.uid() evaluates to NULL. 
-- RLS policies are set TO public (anon) to allow the application to function.
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public view employee photos" ON storage.objects;
CREATE POLICY "Allow public view employee photos" ON storage.objects FOR SELECT TO public 
USING (bucket_id = 'employee-photos');

DROP POLICY IF EXISTS "Allow public insert employee photos" ON storage.objects;
CREATE POLICY "Allow public insert employee photos" ON storage.objects FOR INSERT TO public 
WITH CHECK (bucket_id = 'employee-photos');

DROP POLICY IF EXISTS "Allow public update employee photos" ON storage.objects;
CREATE POLICY "Allow public update employee photos" ON storage.objects FOR UPDATE TO public 
USING (bucket_id = 'employee-photos');

DROP POLICY IF EXISTS "Allow public view attendance photos" ON storage.objects;
CREATE POLICY "Allow public view attendance photos" ON storage.objects FOR SELECT TO public 
USING (bucket_id = 'attendance-photos');

DROP POLICY IF EXISTS "Allow public insert attendance photos" ON storage.objects;
CREATE POLICY "Allow public insert attendance photos" ON storage.objects FOR INSERT TO public 
WITH CHECK (bucket_id = 'attendance-photos');

-- 4. Cleanup Strategy (Edge Function compatible)
-- Queue table for the Edge Function to process
CREATE TABLE IF NOT EXISTS public.storage_cleanup_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bucket_id TEXT NOT NULL,
  path TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Trigger to queue old employee photos when updated or deleted
CREATE OR REPLACE FUNCTION public.queue_orphaned_employee_photo()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF OLD.photo_path IS NOT NULL AND (NEW.photo_path IS NULL OR NEW.photo_path <> OLD.photo_path) THEN
      INSERT INTO public.storage_cleanup_queue (bucket_id, path) VALUES ('employee-photos', OLD.photo_path);
    END IF;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    IF OLD.photo_path IS NOT NULL THEN
      INSERT INTO public.storage_cleanup_queue (bucket_id, path) VALUES ('employee-photos', OLD.photo_path);
    END IF;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS on_employee_photo_modified ON public.funcionarios;
CREATE TRIGGER on_employee_photo_modified
  AFTER UPDATE OF photo_path OR DELETE ON public.funcionarios
  FOR EACH ROW
  EXECUTE FUNCTION public.queue_orphaned_employee_photo();

-- Function to queue old attendance photos and clear references
CREATE OR REPLACE FUNCTION public.queue_old_attendance_photos()
RETURNS void AS $$
BEGIN
  -- 1. Insert into cleanup queue
  INSERT INTO public.storage_cleanup_queue (bucket_id, path)
  SELECT 'attendance-photos', photo_path 
  FROM public.presencas 
  WHERE data < (CURRENT_DATE - INTERVAL '15 days')::DATE
  AND photo_path IS NOT NULL;

  -- 2. Clear references from the database
  UPDATE public.presencas 
  SET photo_path = NULL 
  WHERE data < (CURRENT_DATE - INTERVAL '15 days')::DATE
  AND photo_path IS NOT NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Scheduling
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.schedule('queue-old-attendance-photos', '0 0 * * *', 'SELECT public.queue_old_attendance_photos()');
  ELSE
    RAISE NOTICE 'pg_cron is not available. Please configure a Supabase Scheduled Function to execute public.queue_old_attendance_photos() and process the storage_cleanup_queue table.';
  END IF;
END $$;
